game/urls.py
from django.conf.urls import url


from .views import MainView, Game1View, Game2View, IndexView

urlpatterns = [

    url(r'^$', MainView.as_view(), name='main'),
    url(r'^games/$', IndexView.as_view(), name='index'),
    url(r'^game1/$', Game1View.as_view(), name='game1'),
    url(r'^game2/$', Game2View.as_view(), name='game2')

]

hrdep/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import IndexView, EmployDocumentView, DismissDocumentView, ReportView

urlpatterns = [

    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^employ/$', EmployDocumentView.as_view(), name='employ'),
    url(r'^dismiss/$', DismissDocumentView.as_view(), name='dismiss'),
    url(r'^report/$', ReportView.as_view(), name='report'),

]

main/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^hrdep/', include("hrdep.urls", namespace='hrdep')),
    url(r'^', include("game.urls", namespace='game')),

]

game/models.py
from django.db import models

# Create your models here.

hrdep/models.py
from django.db import models
from django.db.models import Q
from django.core.exceptions import ValidationError
# Create your models here.


class StaffManager(models.Manager):

    def all_working(self):
        qs = super(StaffManager, self).filter(~Q(employ_date=None), dismiss_date=None)
        return qs

    def all_new(self):
        qs = super(StaffManager, self).filter(employ_date=None, dismiss_date=None)
        return qs

    def all_employed(self):
        qs = super(StaffManager, self).filter(~Q(employ_date=None))
        return qs

    def all_dismissed(self):
        qs = super(StaffManager, self).filter(~Q(employ_date=None), ~Q(dismiss_date=None))
        return qs


class Staff(models.Model):

    first_name = models.CharField(u'Имя', max_length=255)
    middle_name = models.CharField(u'Отчество', max_length=255)
    last_name = models.CharField(u'Фамилия', max_length=255)
    birthday = models.DateField(u'Дата рождения', blank=True, null=True)
    employ_date = models.DateField(u'Дата приема', blank=True, null=True)
    dismiss_date = models.DateField(u'Дата увольнения', blank=True, null=True)
    post = models.ForeignKey('Post', verbose_name=u'Должность', )

    objects = StaffManager()

    class Meta:
        unique_together = ('first_name', 'middle_name', 'last_name')

    def __str__(self):
        return str(self.get_full_name())

    def get_full_name(self):
        full_name = u' '.join([self.first_name, self.middle_name, self.last_name])
        return full_name
    get_full_name.short_description = u'Полное имя'
    # @property
    # def is_working(self):
    #     if self.employ_date is not None and self.employ_date <= timezone.now().date() and self.dismiss_date is None:
    #         return True
    #     return False
    #
    # @property
    # def is_new(self):
    #     if self.employ_date is None  and self.dismiss_date is None:
    #         return True
    #     return False
    #
    # @property
    # def is_dismiss(self):
    #     if self.employ_date is not None and self.dismiss_date is not None:
    #         return True
    #     return False

class DoesNotCompute(Exception):
    """ Easy to understand naming conventions work best! """
    pass


class Document(models.Model):
    EMPLOYEMENT = 0
    DISMISSION = 1
    DOCUMENT_TYPE = (
        (EMPLOYEMENT, u'Прием на работу'),
        (DISMISSION, u'Увольнение')
    )

    staff = models.ForeignKey('Staff', verbose_name=u'Сотрудник',)
    document_type = models.IntegerField(u'Тип документа', choices=DOCUMENT_TYPE, null=True)
    date = models.DateTimeField(u'Дата', auto_now=True, auto_now_add=False)
    employ_date = models.DateField(u'Дата приема', blank=True, null=True)
    dismiss_date = models.DateField(u'Дата увольнения', blank=True, null=True)
    number = models.IntegerField(u'Номер', unique=True)

    class Meta:
        unique_together = ('staff', 'document_type')

    def save(self, *args, **kwargs):
        staff = self.staff
        staff.employ_date = self.employ_date if staff.employ_date is None else staff.employ_date
        staff.dismiss_date = self.dismiss_date if self.dismiss_date else None
        staff.save()
        super(Document, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.number)


class Post(models.Model):
    name = models.CharField(u'Должность', max_length=255)
    description = models.TextField(u'Описание (не обязательно)', blank=True, null=True)

    def __str__(self):
        return str(self.name)

hrdep/forms.py
from django import forms
from django.utils import timezone

from datetime import datetime

from .models import Document, Staff
from .admin import DocumentCheckedForm


class DateField(forms.DateField):

    def validate(self, value):
        super(DateField, self).validate(value)
        if value > timezone.now().date():
            raise forms.ValidationError('Date is not correct')


class EmployDocumentForm(DocumentCheckedForm):
    employ_date = forms.DateField(widget=forms.SelectDateWidget,
                                  label='Дата приема',
                                  initial=datetime.today().date())
    staff = forms.ModelChoiceField(queryset=Staff.objects.all_new(), label='Сотрудник')

    class Meta:
        model = Document
        fields = ["staff", "employ_date", "number"]


class DismissDocumentForm(DocumentCheckedForm):
    dismiss_date = forms.DateField(widget=forms.SelectDateWidget,
                                   label='Дата увольнения',
                                   initial=datetime.today().date())
    staff = forms.ModelChoiceField(queryset=Staff.objects.all_working(), label='Сотрудник')

    class Meta:
        model = Document
        fields = ["staff", "dismiss_date", "number"]

game/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import ListView, TemplateView, FormView
from django.shortcuts import render


# Create your views here.
class MainView(TemplateView):
    template_name = 'main.html'

class IndexView(TemplateView):
    template_name = 'game/index.html'

class Game1View(TemplateView):
    template_name = 'game/game1.html'

class Game2View(TemplateView):
    template_name = 'game/game2.html'

hrdep/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import ListView, TemplateView, FormView
from django.shortcuts import render


from .forms import EmployDocumentForm, DismissDocumentForm
from .models import Staff

# Create your views here.
class IndexView(TemplateView):
    template_name = 'hrdep/index.html'

class EmployDocumentView(FormView):
    template_name = 'hrdep/form.html'
    initial = {'document_type': '0'}
    form_class = EmployDocumentForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            doc = form.save()
            doc.document_type = doc.EMPLOYEMENT
            doc.save()
            messages.success(request,
                             "Создан документ %s № %s от %s" %
                             (doc.DOCUMENT_TYPE[doc.EMPLOYEMENT][1], doc, doc.date.strftime('%B %d, %Y')))
            return HttpResponseRedirect(reverse('hrdep:index'))

        return render(request, self.template_name, {'form': form})


class DismissDocumentView(FormView):
    template_name = 'hrdep/form.html'
    form_class = DismissDocumentForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            doc = form.save()
            doc.document_type = doc.DISMISSION
            doc.save()
            messages.success(request,
                             "Создан документ %s № %s от %s" %
                             (doc.DOCUMENT_TYPE[doc.DISMISSION][1], doc, doc.date.strftime('%B %d, %Y')))
            return HttpResponseRedirect(reverse('hrdep:index'))

        return render(request, self.template_name, {'form': form})


class ReportView(ListView):
    template_name = 'hrdep/report.html'
    model = Staff

    def get_context_data(self, **kwargs):
        context = super(ReportView, self).get_context_data(**kwargs)
        context['new_staff'] = Staff.objects.all_employed()
        context['dismiss_staff'] = Staff.objects.all_dismissed()
        context['working_staff'] = Staff.objects.all_working()

        return context

templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    {%  block style %}
    {% endblock  %}
</head>
<body>

{% include "massages_display.html" %}
{% block content %}{% endblock content %}
{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.4.8/phaser.min.js"></script>
{% endblock %}
{% block customjs %}
{% endblock customjs %}
</div>

</body>
</html>

templates/game/game1.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Gamedev</title>
{% endblock %}
{% block style %}
<style>
    * { padding: 0; margin: 0; }
    canvas { background: #eee; display: block; margin: 0 auto; }
</style>
{% endblock %}

{% block content %}
    <canvas id="myCanvas" width="480" height="320"></canvas>
{% endblock content %}
{% block customjs %}
    <script src="{% static 'js/game1.js' %}"></script>

{% endblock customjs %}

templates/game/game2.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Gamedev</title>
{% endblock %}
{% block style %}
<style>
    * { padding: 0; margin: 0; }

</style>
{% endblock %}

{% block content %}
{% endblock content %}
{% block customjs %}

    <script type="text/javascript" src="{% static 'js/game2.js' %}"></script>

{% endblock customjs %}

templates/game/index.html
{% extends 'base.html' %}
{% block content %}
<div style="text-align: center;">
<h3><a href="{% url 'game:game1' %}">Just HTML5</a></h3><br>
<h3><a href="{% url 'game:game2' %}">With Phaser</a></h3><br>
    </div>

{% endblock %}

templates/hrdep/form.html
{% extends "base.html" %}
{%  block content %}
    <div style="text-align: center;">
        <form method="POST" action="">{% csrf_token %}{{ form.as_p }}
        <input type="submit" value="OK">
        </form>

    <hr>
<h3><a href="{% url 'hrdep:index' %}">Вернуться на главную</a></h3>
    </div>
{% endblock %}

templates/hrdep/index.html
{% extends "base.html" %}
{%  block content %}
    <div style="text-align: center;">
<h3><a href="{% url 'hrdep:employ' %}">Employ</a></h3><br>
<h3><a href="{% url 'hrdep:dismiss' %}">Dismiss</a></h3><br>
<h3><a href="{% url 'hrdep:report' %}">Report</a></h3>
    </div>
{% endblock %}

templates/hrdep/report.html
{% extends "base.html" %}
{%  block content %}

<div>Принятые:
{{ new_staff.count }}
<br><ul>
    {% for st in new_staff %}
    <li>{{ st }}</li>
    {% endfor %}
</ul>
</div>
<div>Работающие:
{{ working_staff.count }}
<br><ul>
    {% for st in working_staff %}
    <li>{{ st }}</li>
    {% endfor %}
</ul>
</div>
<div>Уволенные:
{{ dismiss_staff.count }}
<br><ul>
    {% for st in dismiss_staff %}
    <li>{{ st }}</li>
    {% endfor %}
</ul>
<hr>
<h3><a href="{% url 'hrdep:index' %}">Вернуться на главную</a></h3>

    </div>
{% endblock %}

templates/main.html
{% extends "base.html" %}
{%  block content %}
    <div style="text-align: center;">
<h3><a href="{% url 'hrdep:index' %}">Hrdep</a></h3><br>
<h3><a href="{% url 'game:index' %}">Game</a></h3><br>
    </div>
{% endblock %}

templates/massages_display.html
{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}